name: .NET Core Test

on: pull_request

env:
  DOTNET_VERSION: 3.0.100

jobs:

  Test:
    runs-on: ubuntu-latest
    steps:
    - name: Chectout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    - name: Check format
      run: |
        dotnet tool install --tool-path ./ dotnet-format
        ./dotnet-format --check --dry-run -v diagnostic
    - name: Build
      run: dotnet publish -o ./out -c Release
    - name: Install dependencies
      run: sudo apt-get install libleveldb-dev expect
    - name: Run tests with expect
      run: expect ./.github/workflows/test-neo-cli.expect
    - name: Run RPC tests
      run: ./.github/workflows/rpc-tests.sh
